### ISSUE TITLE
Default collision type for body must be NullCollision

### ISSUE THREAD

**Issue by KionX** [MADEAPPS/newton-dynamics#49]
Default collision pointer is null.
The pointer must specify to a Null collision type
or calculations of the collision should be ignored.

**Comment by JulioJerez** [comment]
is this a bug?

**Comment by KionX** [comment]
this uncomfortable behaviour

**Comment by JulioJerez** [comment]
Uncomfortable behavior, what does that mean I do not understand.

**Comment by KionX** [comment]
If create body as
NewtonCreateDynamicBody(World, null, Matrix);
it throw exception in NewtonUpdate

the right to create so:
Collision=NewtonCreateNull;
Body=NewtonCreateDynamicBody(World, null, Matrix);
NewtonBodySetCollision(Body, Collision);

NewtonCreateNull meaningless, not needed

NewtonBodySetCollision(Body, null);
must be equivalent
Collision=NewtonCreateNull;
NewtonBodySetCollision(Body, Collision);

also CollisionNull has no parameters
it serialization is meaningless

**Comment by JulioJerez** [comment]
oh I see you what to pass null for bodies passing null for null collisions.
I suppose that will be a short cut, by I prefect a uniform interface, each body must have a collision pointer 

NewtonCreateNull is not meaningless, the engine expect all bodies to have a non null collision shape, doing otherwise mean I will have to check all places when a collision is used an test for null, which can   can be several tenths of thousand of time during an update.

you must doing the second way
Collision=NewtonCreateNull;
NewtonBodySetCollision(Body, Collision); 

sorry for that inconvenient 
are you having problems with that and serialization?

**Comment by KionX** [comment]
I had inconvenience because of this behavior
and I decided in a similar way:

NewtonCreateNull you can call NewtonCreate
and implicitly assign in
NewtonBodySetCollision and NewtonCreateBody

**Comment by JulioJerez** [comment]
Yes I suppose I can do that on the engine side, but that makes the engine interface unnecessarily  complex for little benefit. Newton is suppose to be a low level library I do no like to add extra interfaces that is the end application can write a wrapper for it.
similar to that, people always ask for feature like stuff like forces at a point, and I do no add that to the engine because it can be done by using a cross product, 
this case is similar, you can write and wrapper function like 

MyCreateNewton (world, shape, matrix)
{
  if (shape == null)
 {
     shape = NewtonCreateNull();
     NewtonCreateBody(world, shape, matrix)
     NetwonDeletShape(shape)
} 
else 
{  
   NewtonCreateBody(world, shape, matrix)
}
} 

I actually do that for Collision shape matrices, but is a pain in the neck  to keep adding permutations of parameters. 
I hope this is Ok solution for you.

**Comment by KionX** [comment]
It is unnecessary to add extra interfaces

I propose add to the class constructor dgWorld
m_nullShape = NewtonCreateNull();
and to dgBody::AttachCollision
if (!collisionSrc) {
    collisionSrc = m_world->m_nullShape;
}

**Comment by JulioJerez** [comment]
ok, I just added that functionality,  please sync and let me know

**Comment by KionX** [comment]
in general, this is what I wanted
but I don't understand why create a null collision for every body

I can propose my solution?

**Comment by JulioJerez** [comment]
what do you mean it create a null collision for each body? it is not, 
it creates a null collision only when the pointer is null, The engine has internal cache system so in no making new collision.  you cna check that the pointer to the shapes is the same
this is the function

```
NewtonBody* NewtonCreateDynamicBody(const NewtonWorld* const newtonWorld, const NewtonCollision* const collisionPtr, const dFloat* const matrixPtr)
{
	TRACE_FUNCTION(__FUNCTION__);
	Newton* const world = (Newton *)newtonWorld;
	dgCollisionInstance* collision = (dgCollisionInstance*)collisionPtr;
	if (!collisionPtr) {
		collision = (dgCollisionInstance*) NewtonCreateNull(newtonWorld);
	}

	#ifdef SAVE_COLLISION
	SaveCollision (collisionPtr);
	#endif

	dgMatrix matrix (matrixPtr);
#ifdef _DEBUG
	//	matrix.m_front = matrix.m_front.Scale3 (dgRsqrt (matrix.m_front % matrix.m_front));
	//	matrix.m_right = matrix.m_front * matrix.m_up;
	//	matrix.m_right = matrix.m_right.Scale3 (dgRsqrt (matrix.m_right % matrix.m_right));
	//	matrix.m_up = matrix.m_right * matrix.m_front;
#endif

	matrix.m_front.m_w = dgFloat32 (0.0f);
	matrix.m_up.m_w    = dgFloat32 (0.0f);
	matrix.m_right.m_w = dgFloat32 (0.0f);
	matrix.m_posit.m_w = dgFloat32 (1.0f);

	NewtonBody* const body = (NewtonBody*)world->CreateDynamicBody (collision, matrix);
	if (!collisionPtr) {
		NewtonDestroyCollision((NewtonCollision*)collision);
	}
	return body;
}

```

**Comment by KionX** [comment]
I used the wrong words.
Even internal cache system for them redundant.

**Comment by JulioJerez** [comment]
not that will not work, when a body is created, the collision shape get its reference count incremented, 
assigning the pointer will cause a crash when the body is going to be destroyed.

**Comment by KionX** [comment]
CreateNull - collision reference count +1
CreateDynamicBody (collision) - collision reference count +1
DestroyBody - collision reference count -1

I this so understand...

**Comment by JulioJerez** [comment]
ok, now we agree
